name: build

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Java setup
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: 16
          cache: "gradle"
      - name: Permissions stuff
        run: chmod +x gradlew
      - name: Build
        run: ./gradlew build
      - name: Rename build artifacts
        run: mv build/libs/BanAnimations.jar build/libs/BanAnimations-${{ github.event.head_commit.id }}.jar
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: BanAnimations
          path: build/libs/BanAnimations-${{ github.event.head_commit.id }}.jar